/**
 * build-server.mjs
 *
 * Assembles a minimal Minecraft server package and zips it into build/.
 *
 * Sources (layered into build/server/, then zipped):
 *   - server-files/        → run scripts, eula, server.properties
 *   - overrides/config/    → modpack config
 *   - overrides/kubejs/    → KubeJS scripts
 *   - generated install scripts that fetch NeoForge and server payloads
 *
 * NeoForge and mods are NOT included in the archive.
 *
 * Output:
 *   build/server/                        assembled server (unzipped)
 *   build/universum-server-v{ver}.zip    final archive
 *
 * Usage:
 *   node scripts/build-server.mjs
 *
 * Optional env vars (see .env.example):
 *   SERVER_NEOFORGE_VERSION — NeoForge version to fetch (default from modpack manifest)
 *   SERVER_PAYLOAD_URL      — optional URL to download additional server payloads
 */

import { join, basename } from 'path';
import { createWriteStream } from 'fs';
import { promises as fs } from 'fs';
import archiver from 'archiver';
import { transferFull } from './lib/transfer.mjs';
import { overridesDir, rootDir, buildDir } from './cfg.mjs';
import packageJson from '../package.json' with { type: 'json' };
import manifestJson from '../modpack/manifest.json' with { type: 'json' };

const serverFilesDir = join(rootDir, 'server-files');
const outputDir = join(buildDir, 'server');
const outputZip = join(buildDir, `universum-server-v${packageJson.version}.zip`);
const neoForgeVersion = process.env.SERVER_NEOFORGE_VERSION || manifestJson.minecraft.modLoaders[0].id.replace('neoforge-', '');
const SERVER_FILES_EXCLUDE = [
    /^libraries[\\/]/,
    /^mods[\\/]/,
    /^logs[\\/]/,
    /^world[\\/]/,
];

async function zipDir(sourceDir, zipPath) {
    await fs.mkdir(join(zipPath, '..'), { recursive: true });
    const output = createWriteStream(zipPath);
    const archive = archiver('zip', { zlib: { level: 1 } }); // level 1 = fast, server JARs don't compress well

    archive.pipe(output);
    archive.directory(sourceDir, false);

    await new Promise((resolve, reject) => {
        output.on('close', resolve);
        archive.on('error', reject);
        archive.finalize();
    });

    const { size } = await fs.stat(zipPath);
    console.log(`ZIP created: ${basename(zipPath)} (${(size / 1024 / 1024).toFixed(0)} MB)`);
}

function renderInstallScript() {
    return `#!/usr/bin/env sh
set -eu

NEOFORGE_VERSION="${neoForgeVersion}"
INSTALLER_URL="https://maven.neoforged.net/releases/net/neoforged/neoforge/${neoForgeVersion}/neoforge-${neoForgeVersion}-installer.jar"
INSTALLER_JAR="neoforge-${neoForgeVersion}-installer.jar"
SERVER_PAYLOAD_URL="${process.env.SERVER_PAYLOAD_URL || ''}"

echo "Downloading NeoForge ${neoForgeVersion} installer..."
curl -fsSL -o "$INSTALLER_JAR" "$INSTALLER_URL"

echo "Installing NeoForge server..."
java -jar "$INSTALLER_JAR" --installServer

if [ -n "$SERVER_PAYLOAD_URL" ]; then
  echo "Downloading server payload..."
  curl -fsSL -o server-payload.zip "$SERVER_PAYLOAD_URL"
  echo "Unpacking server payload..."
  unzip -o server-payload.zip -d .
  rm -f server-payload.zip
fi

rm -f "$INSTALLER_JAR"
echo "Done."
`;
}

async function writeInstallers() {
    await fs.writeFile(join(outputDir, 'install.sh'), renderInstallScript(), 'utf8');
    await fs.writeFile(join(outputDir, 'install.bat'), `@echo off\r\nREM Minimal server installer is generated by build-server.mjs\r\nREM Use install.sh on Linux or adapt this script for Windows.\r\n`, 'utf8');
}

async function main() {
    console.log(`NeoForge version: ${neoForgeVersion}`);
    console.log(`Output dir:      ${outputDir}\n`);

    await fs.rm(outputDir, { recursive: true, force: true });
    await transferFull(serverFilesDir, outputDir, 'server-files', { dryRun: false, verbose: false, exclude: SERVER_FILES_EXCLUDE });
    await transferFull(join(overridesDir, 'config'), join(outputDir, 'config'), 'config', { dryRun: false, verbose: false });
    await transferFull(join(overridesDir, 'kubejs'), join(outputDir, 'kubejs'), 'kubejs', { dryRun: false, verbose: false });
    await writeInstallers();

    console.log('\nZipping...');
    await zipDir(outputDir, outputZip);

    console.log('=== Build complete. ===');
}

main().catch(err => { console.error(err); process.exit(1); });
