#ToLaserBlade's client side settings.
[client]
	#Enable to show update message.
	#Default: true
	showUpdateMessage = true
	#Using mod model loader to load Laser Blade models. Set to false to use the model that loaded by vanilla model loader.
	#Need to reload resource packs after changing this.
	#Default: true
	useOriginalModelType = true
	#Enable to render Laser Blades using multiple models. This setting is valid when useOriginalModelLoader is true.
	#Set to false to use the model of defaultModelType.
	#Need to reload resource packs after changing this.
	#Default: true
	renderMultipleModels = true
	#Select model number of laser blade to use when renderMultipleModels is false. This setting is valid when useOriginalModelType is true.
	#Need to reload resource packs after changing this.
	#Default: 0
	# Default: 0
	# Range: > 0
	defaultModel = 0
