name: Upload to CurseForge (Tag Release)

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: "--dns-result-order=ipv4first"

    steps:
      - name: Check internet connection with curl and timeout
        run: curl --connect-timeout 10 --max-time 30 -I minecraft.curseforge.com

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build ZIP archive
        run: node scripts/build.mjs

      - name: Upload to CurseForge
        env:
          CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
          CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
        run: node scripts/upload.mjs